EMAIL_ACCOUNTS:
  JOB:
    SMTP_SERVER: smtp.hostinger.com
    SMTP_PORT: '465'
    SMTP_USERNAME: ${JOB_SMTP_USERNAME}
    SMTP_PASSWORD: ${JOB_SMTP_PASSWORD}

  COURSE:
    SMTP_SERVER: smtp.hostinger.com
    SMTP_PORT: '465'
    SMTP_USERNAME: ${SMTP_COURSE_USERNAME}
    SMTP_PASSWORD: ${SMTP_COURSE_PASSWORD}
